### ISSUE TITLE
report connect.kak in starship prompt

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/connect.kak#46]
This works fine in [starship prompt](https://starship.rs/):

```toml
[custom.connect_kak]
command = "echo 'kak '"
when = 'test -n "$IN_KAKOUNE_CONNECT"'
description = "Indicates that the current shell is connected to a Kakoune session"
style = "green italic"
```

**Comment by alexherbo2** [comment]
You can indicate the Kakoune session and client when in a connected terminal.

When connected to a client:

``` sh
${KAKOUNE_CLIENT}@${KAKOUNE_SESSION}
```

When connected to a session:

``` sh
${KAKOUNE_SESSION}
```

**Comment by basbebe** [comment]
```toml
[custom.connect_kak]
command = "echo 'kak:'$KAKOUNE_CLIENT@$KAKOUNE_SESSION"
when = 'test -n "$IN_KAKOUNE_CONNECT"'
description = "Indicates that the current shell is connected to a Kakoune session"
style = "green italic"
```

<img width="241" alt="Bildschirmfoto 2021-02-02 um 13 57 21" src="https://user-images.githubusercontent.com/7083188/106603437-32deff00-6556-11eb-8b4c-4b421cc6ee68.png">

**Comment by alexherbo2** [comment]
In some scenarios, when using the `kak-shell` program for example, you can be connected to a session without a client, so you may want to test both cases.

**Comment by basbebe** [comment]
> In some scenarios, when using the `kak-shell` program for example, you can be connected to a session without a client, so you may want to test both cases.

When and how would this happen?

**Comment by basbebe** [comment]
```toml
[custom.connect_kak]
command = "echo 'kak:'$( test -n \"$KAKOUNE_CLIENT\" && echo $KAKOUNE_CLIENT@)$KAKOUNE_SESSION"
when = 'test -n "$IN_KAKOUNE_CONNECT"'
shell = ["sh", "--norc"]
description = "Indicates that the current shell is connected to a Kakoune session"
style = "green italic"

```

**Comment by alexherbo2** [comment]
@basbebe If it’s [TOML], I would go with multi-line literal strings or two prompts.

``` toml
[custom.kakoune_connect_client]
command = 'printf "🐈(${KAKOUNE_CLIENT}@${KAKOUNE_SESSION})"'
when = 'test "$IN_KAKOUNE_CONNECT" = 1 -a -n "$KAKOUNE_SESSION" -a -n "$KAKOUNE_CLIENT"'
shell = ['dash']
description = 'Indicates that the current shell is connected to a Kakoune client'
style = 'green italic'

[custom.kakoune_connect_session]
command = 'printf "🐈(${KAKOUNE_SESSION})"'
when = 'test "$IN_KAKOUNE_CONNECT" = 1 -a -n "$KAKOUNE_SESSION" -a -z "$KAKOUNE_CLIENT"'
shell = ['dash']
description = 'Indicates that the current shell is connected to a Kakoune session'
style = 'green italic'
```

Or

``` toml
command = '''
  if [ "$KAKOUNE_CLIENT" ]; then
    ...
  else
    ...
  fi
'''
```

I prefer the first because `command` is not intended for testing.

[TOML]: https://toml.io
